<a href="https://colab.research.google.com/github/JIN-HAN2025/AICE-python-practice/blob/main/02_20251227_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EA%B8%B0%EC%B4%88%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#numpu : numerical python 수치 데이터처리 라이브러리
import numpy as np

#1차원 배열
array = np.array([1,2,3,4,5])
print(array)
print("배열의 자료형:",array.dtype)


[1 2 3 4 5]
배열의 자료형: int64


In [12]:
#2차원 배열 : 행과 열로 구성
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix[0])

#배열의 크기;배열의 총 요소 개수
print('배열의 크기',matrix.size)
#배열의 형태 : 배열의 행과 열의 개수
print("배열의 형태",matrix.shape)
#배열의 차원 확인
print("배열의 차원:",matrix.ndim)

[[1 2 3]
 [4 5 6]]
[1 2 3]
배열의 크기 6
배열의 형태 (2, 3)
배열의 차원: 2


In [17]:
#배열의 연산
#배열의 합:모든 요소의 합
print("배열의 합:",np.sum(matrix))
#배열의 평균: 모든 요소의 평균
print("배열의 평균:",np.mean(matrix))
#배열의 최소값
print("배열의 최소값:",np.min(matrix))
#배열의 최대값
print("배열의 최대값:",np.max(matrix))

배열의 합: 21
배열의 평균: 3.5
배열의 최소값: 1
배열의 최대값: 6


In [18]:
#배열의 전치 : 행과 열을 뒤바꾸는 것
transposed = matrix.T # 행과 열을 바꿈
print("전치된 배열:",transposed)

전치된 배열: [[1 4]
 [2 5]
 [3 6]]


In [20]:
#pandas : 테이블 형태의 데이터를 다루기 위한 라이브러리
import pandas as pd

#Series 생성 : 1차원 데이터 구조로 인덱스를 함께 저장
data = [10,20,30,40,50]
series = pd.Series(data)
print("Series 데이터:\n",series)
print("첫번째 값:",series[0])

Series 데이터:
 0    10
1    20
2    30
3    40
4    50
dtype: int64
첫번째 값: 10


In [22]:
#DataFrame : 행과 열로 구성된 2차원 데이터 구조, 엑셀 표
#딕셔너리를 사용해 DataFrame 생성
data={
    "이름":['김철수','이영희','박민수'],
    "수학":[85,90,78],
    "영어":[88,84,95]
}
df = pd.DataFrame(data)
print("data:\n",data)
print("DataFrame:\n",df)
df

data:
 {'이름': ['김철수', '이영희', '박민수'], '수학': [85, 90, 78], '영어': [88, 84, 95]}
DataFrame:
     이름  수학  영어
0  김철수  85  88
1  이영희  90  84
2  박민수  78  95


이름  수학  영어
0  김철수  85  88
1  이영희  90  84
2  박민수  78  95